First API route complete for GET project by id
jump-starter/johnny-product-summary-module pull request #1
Opened 2018-05-08 22:17 UTC by zhujohnny

2018-05-08 22:46 UTC, CareyL96 commented on client/src/components/Stats.js
> +            ${this.props.data.total_pledge_amt}
no snake case

2018-05-08 22:47 UTC, careyl96 requested changes
change variables to non-snake case

2018-05-08 22:47 UTC, CareyL96 commented on client/src/components/Stats.js
> +            ${this.props.data.total_pledge_amt}
no snake case

2018-05-08 22:47 UTC, CareyL96 commented on client/src/components/Stats.js
> +          <div>pledged of {this.props.data.goal_amt} goal</div>
no snake case

2018-05-08 22:47 UTC, CareyL96 commented on client/src/components/Stats.js
> +          <div style={style.nums}>{this.props.data.pledges_count}</div>
no snake case

2018-05-09 02:54 UTC, zhujohnny commented on client/src/components/Stats.js
> +            ${this.props.data.total_pledge_amt}
Changed to camelCase

2018-05-09 02:54 UTC, zhujohnny commented on client/src/components/Stats.js
> +          <div>pledged of {this.props.data.goal_amt} goal</div>
Changed to camelCase

2018-05-09 02:54 UTC, zhujohnny commented on client/src/components/Stats.js
> +          <div style={style.nums}>{this.props.data.pledges_count}</div>
Changed to camelCase

2018-05-09 02:55 UTC, closed without merging